spring.application.name=tool_rental_api

spring.datasource.url=jdbc:postgresql://localhost:5432/tool_rental
spring.datasource.username=tool_rental
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=200
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

server.port=8080

app.jwt.secret=tool-rental-super-secret-key-must-be-at-least-32-chars